[[artifacts]]
version = "9.4.8.0"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com/heroku-24/ruby-3.1.4-jruby-9.4.8.0-dd073bd.tgz"
checksum = "sha256:dd073bda5665e758c3e6f861a6df435175c8e8faf5ec75bc2afaab1e3eebb2c7"

[artifacts.metadata]
timestamp = "2024-07-24T16:17:35.341413Z"
distro_version = "24.04"

[[artifacts]]
version = "9.4.8.0"
os = "linux"
arch = "arm64"
url = "https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com/heroku-24/ruby-3.1.4-jruby-9.4.8.0-dd073bd.tgz"
checksum = "sha256:dd073bda5665e758c3e6f861a6df435175c8e8faf5ec75bc2afaab1e3eebb2c7"

[artifacts.metadata]
timestamp = "2024-07-24T16:17:35.341917Z"
distro_version = "24.04"

