FROM heroku/heroku:22-build

# setup workspace
RUN rm -rf /tmp/workspace
RUN mkdir -p /tmp/workspace

RUN apt-get update -y; apt-get install ruby -y

# output dir is mounted

ADD build.rb /tmp/build.rb
CMD ["ruby", "/tmp/build.rb", "/tmp/workspace", "/tmp/output", "/tmp/cache"]
