FROM heroku/heroku:20-build

RUN gem install bundler

# setup workspace
RUN rm -rf /tmp/workspace
RUN mkdir -p /tmp/workspace

WORKDIR /root/work

# output dir is mounted
ADD build.rb /tmp/build.rb
CMD ["ruby", "/tmp/build.rb", "/tmp/workspace", "/tmp/output", "/tmp/cache"]

COPY dockerfiles/support/entrypoint.sh /usr/bin/entrypoint.sh

ENTRYPOINT ["/usr/bin/entrypoint.sh"]
