name: CI

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Linting
        run: bundle exec standardrb

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: test
        run: bundle exec rspec spec

  integration_test:
      runs-on: pub-hk-ubuntu-22.04-xlarge
      env:
        STACK: "heroku-22"
        TEST_VERSION: "3.1.4"
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up Ruby
          uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
          with:
            ruby-version: '3.1'
        - name: Install dependencies
          run: bundle install
        - name: Output CHANGELOG
          run: bundle exec rake "changelog[$TEST_VERSION]"
        - name: Build Docker image
          run: bundle exec rake "generate_image[$STACK]"
        - name: Generate Ruby Dockerfile
          run: bundle exec rake "new[$TEST_VERSION,$STACK]"
        - name: Build and package Ruby runtime
          run: bash "rubies/$STACK/ruby-$TEST_VERSION.sh"
        - name: Verify ruby executable and output rubygems version
          run: bundle exec rake "rubygems_version[$TEST_VERSION,$STACK]"


